app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

class User(db.Model,UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255), nullable = False)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String)
    post = db.relationship('Blog', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')
    

    @property
    def password(self):
        raise AttributeError('Password attribute cannot be read')
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)


    def __repr__(self):
        return f'User {self.username}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Blog(db.Model):
    __tablename__="blogs"
    
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    blog = db.Column(db.Text())
    author_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comment = db.relationship('Comment', backref='blog', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Blog {self.title}'

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.Text,nullable = False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()
    
    def __repr__(self):
        return f'Comment {self.comment}'


class Quotes:
 def __init__ (self,author,quote,permalink):
   self.author = author
   self.quote = quote
   self.permalink = permalink
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired, Required
from app.models import Blog,Comment

class NewblogForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    blog = TextAreaField('Blog', validators=[DataRequired()])
    submit = SubmitField('Add Blog', validators=[DataRequired()])

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment something',validators = [Required()])
    submit = SubmitField('Post Comments')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager,login_manager,login_user

app =  Flask(__name__)
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    #initialising blueprints
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, forms

app/main/views.py
from flask import render_template, redirect,url_for,request,flash
from . import main
from flask_login import login_required,current_user
from ..models import Blog,Comment
from .forms import NewblogForm,CommentForm
from .. import db
from app.request import getQuotes

# Views
@main.route('/')
def index():
    quote = getQuotes()
    title = 'Home - Fine Blog'
    print(quote)
    blogs = Blog.query.all()
    blogs = blogs[::-1]
    return render_template('index.html',title = title,quote = quote,blogs=blogs)

@main.route('/newblog',methods = ["GET","POST"])
@login_required
def newblog():
    form = NewblogForm()
    if form.validate_on_submit():
        blog = Blog (title = form.title.data, blog = form.blog.data,author_id = current_user._get_current_object().id)
        blog.save()
        flash('Post created succesfully')
        return redirect(url_for('main.index'))
    return render_template('newblog.html',form = form)


@main.route('/edit_blog/<blog_id>/edit',methods = ["GET","POST"])
@login_required
def edit_blog(blog_id):
    form = NewblogForm()
    blog = Blog.query.get(blog_id)
    if current_user != blog.user:
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        blog.title = form.title.data
        blog.blog = form.blog.data
        db.session.commit()
        return redirect(url_for('main.index'))
    if request.method == 'GET':
        form.title.data = blog.title
        form.blog.data = blog.blog
    return render_template ('newblog.html',form = form)

@main.route('/blog/<blog_id>/delete',methods = ["GET","POST"])
@login_required
def deleteblog(blog_id):
    blog = Blog.query.get(blog_id)
    if current_user != blog.user:
        return redirect(url_for('main.index'))
    db.session.delete(blog)
    db.session.commit()
    flash('Deleted Succesfully')
    return redirect(url_for('main.index'))

@main.route('/newcomment/<blog_id>',methods = ["GET","POST"])
@login_required
def newcomment(blog_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(comment = form.comment.data, blog_id = blog_id, user_id = current_user._get_current_object().id )
        new_comment.save()
        return redirect (url_for('main.index'))
    return render_template('comment.html', form = form )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block style %}   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> 
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">    
    {% endblock %}

</head>
<body>
        {% block navbar %}
        {% include "navbar.html" %}
        {% endblock %}
        {% block content %}


        
        {% endblock %}

        {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% endblock %}
    
</body>
</html>

app/templates/blog.html
{% block styles %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="container">
        <large>{{pitch.pitch_title}}</large>
        <hr>
        <p>{{pitch.pitch_content}}</p>
    </div>
    <div>
        <p>Comments</p>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(comment_form) }}
        {%endif%}

    </div>
    <div class="col-md-3"></div>
<div class="col-md-6">
    <p>Comments</p>
    <br>
    {% if current_user.is_authenticated %}
        {{ wtf.quick_form(comment_form) }}
    {%endif%}
</div>
<div class="col-md-3"></div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}


{% block styles %}
    {{ super() }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        {{wtf.quick_form(form)}}
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% block style %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}
<div class="page-header" style="text-align:center; font-family: 'Abril Fatface', cursive">
    <h1>Fine Blog</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="Jumbotron">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
                {% if current_user.is_authenticated %}
                <a href="{{url_for('main.newblog')}}" class="btn btn-info btn-sm mb-3">Add Post</a>
                {% endif %}
                {% for blog in blogs %}
                <div class="card" style="margin-bottom: 20px">
                    <div class="card-header">
                        {{blog.title}}
                    </div>
                    <div class="card-body">
                        <p>{{blog.blog}}</p>
                        <h5>By: {{blog.user.username}}</h5>
                        <a class="btn btn-success btn-sm"
                            href="{{url_for('main.newcomment', blog_id = blog.id)}}">Comment</a>
                        {% if current_user.is_authenticated %}
                        <a class="btn btn-info btn-sm" href="{{url_for('main.edit_blog',blog_id = blog.id)}}">Edit</a>
                        <a class="btn btn-danger btn-sm"
                            href="{{url_for('main.deleteblog',blog_id = blog.id)}}">Delete</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="well well-lg">
                <div class="page-header" style="text-align: center">Randomn Quotes</div>
                <div class="card" style="text-align:center; background-color:orange">
                    <div class="row">
                        <div class="col-md-12">
                            <p>{{quote.quote}}</p>
                            <p>{{quote.author}}</p>
                            <a href="{{quote.permalink}}">Read</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-inverse bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><strong>Fine Blogs</strong></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{url_for('main.index')}}">Blogs</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li style="color:white;padding:15px;">{{current_user.username}}</li>
      <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li><a href="{{url_for('auth.register')}}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{{url_for('auth.login')}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/newblog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
    <h4>Add post</h4>
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

    {{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}